export default [
  { filename: "osa_arrow_green_left.svg", name: "arrow_green_left" },
  { filename: "osa_arrow_yellow_right.svg", name: "arrow_yellow_right" },
  { filename: "osa_awareness.svg", name: "awareness" },
  { filename: "osa_camera-web.svg", name: "camera-web" },
  { filename: "osa_cloud.svg", name: "cloud" },
  { filename: "osa_contract.svg", name: "contract" },
  { filename: "osa_database.svg", name: "database" },
  { filename: "osa_desktop_imac.svg", name: "desktop_imac" },
  { filename: "osa_desktop.svg", name: "desktop" },
  { filename: "osa_device-music.svg", name: "device-music" },
  { filename: "osa_device-scanner.svg", name: "device-scanner" },
  { filename: "osa_device-usb.svg", name: "device-usb" },
  { filename: "osa_device-usb-wifi.svg", name: "device-usb-wifi" },
  {
    filename: "osa_device-wireless-router.svg",
    name: "device-wireless-router",
  },
  { filename: "osa_disposal.svg", name: "disposal" },
  { filename: "osa_drive-harddisk.svg", name: "drive-harddisk" },
  { filename: "osa_drive-optical.svg", name: "drive-optical" },
  { filename: "osa_firewall.svg", name: "firewall" },
  { filename: "osa_home.svg", name: "home" },
  { filename: "osa_hub.svg", name: "hub" },
  { filename: "osa_ics_drive.svg", name: "ics_drive" },
  { filename: "osa_ics_plc.svg", name: "ics_plc" },
  { filename: "osa_ics_thermometer.svg", name: "ics_thermometer" },
  { filename: "osa_id_card.svg", name: "id_card" },
  { filename: "osa_image-generic.svg", name: "image-generic" },
  { filename: "osa_iPhone.svg", name: "iPhone" },
  { filename: "osa_laptop.svg", name: "laptop" },
  { filename: "osa_lifecycle.svg", name: "lifecycle" },
  { filename: "osa_lightning.svg", name: "lightning" },
  { filename: "osa_media-flash.svg", name: "media-flash" },
  { filename: "osa_media-optical.svg", name: "media-optical" },
  { filename: "osa_media-tape.svg", name: "media-tape" },
  { filename: "osa_mobile_pda.svg", name: "mobile_pda" },
  { filename: "osa_padlock.svg", name: "padlock" },
  { filename: "osa_printer.svg", name: "printer" },
  { filename: "osa_server_application.svg", name: "server_application" },
  { filename: "osa_server_database.svg", name: "server_database" },
  { filename: "osa_server_directory.svg", name: "server_directory" },
  { filename: "osa_server_distribution.svg", name: "server_distribution" },
  { filename: "osa_server_file.svg", name: "server_file" },
  { filename: "osa_server_gateway.svg", name: "server_gateway" },
  { filename: "osa_server_identity.svg", name: "server_identity" },
  { filename: "osa_server_mail.svg", name: "server_mail" },
  { filename: "osa_server_media.svg", name: "server_media" },
  { filename: "osa_server_monitor.svg", name: "server_monitor" },
  { filename: "osa_server_proxy.svg", name: "server_proxy" },
  { filename: "osa_server.svg", name: "server" },
  { filename: "osa_server_terminal.svg", name: "server_terminal" },
  { filename: "osa_server_web.svg", name: "server_web" },
  { filename: "osa_site-branch.svg", name: "site-branch" },
  { filename: "osa_site-factory.svg", name: "site-factory" },
  { filename: "osa_site-head-office.svg", name: "site-head-office" },
  { filename: "osa_site-neighbourhood.svg", name: "site-neighbourhood" },
  { filename: "osa_user_audit.svg", name: "user_audit" },
  { filename: "osa_user_black_hat.svg", name: "user_black_hat" },
  {
    filename: "osa_user_blue_security_specialist.svg",
    name: "user_blue_security_specialist",
  },
  { filename: "osa_user_blue.svg", name: "user_blue" },
  { filename: "osa_user_blue_sysadmin.svg", name: "user_blue_sysadmin" },
  { filename: "osa_user_blue_tester.svg", name: "user_blue_tester" },
  { filename: "osa_user_blue_tie.svg", name: "user_blue_tie" },
  {
    filename: "osa_user_green_architect.svg",
    name: "user_green_architect",
  },
  {
    filename: "osa_user_green_business_manager.svg",
    name: "user_green_business_manager",
  },
  {
    filename: "osa_user_green_developer.svg",
    name: "user_green_developer",
  },
  {
    filename: "osa_user_green_operations.svg",
    name: "user_green_operations",
  },
  {
    filename: "osa_user_green_project_manager.svg",
    name: "user_green_project_manager",
  },
  {
    filename: "osa_user_green_service_manager.svg",
    name: "user_green_service_manager",
  },
  { filename: "osa_user_green.svg", name: "user_green" },
  { filename: "osa_user_green_warning.svg", name: "user_green_warning" },
  { filename: "osa_user_large_group.svg", name: "user_large_group" },
  { filename: "osa_users_blue_green.svg", name: "users_blue_green" },
  { filename: "osa_user_white_hat.svg", name: "user_white_hat" },
  { filename: "osa_vpn.svg", name: "vpn" },
  { filename: "osa_warning.svg", name: "warning" },
  { filename: "osa_wireless_network.svg", name: "wireless_network" },
];
